### PR TITLE
feat: added trouble.nvim integration

### LINKED ISSUE #238: [Feature Request] integeration with Trouble.nvim
I think it's safe to say integration with Trouble quickfix list would be great

### PR DESCRIPTION
**Pull request by Std-Enigma**
## Description

This PR adds trouble.nvim integration to send entries to trouble.nvim quickfix list.

## Changes

- Added use_trouble_qf flag to the config table
- Updated send_to_qf action logic
- Updated README

## Related Issues

Closes #238

### CODE REVIEW

**Comment by EpsilonKu** [comment]
Can you add `use_trouble_qf = false` to Readme?

**Comment by Std-Enigma** [comment]
done updated REDAME

**Comment by EpsilonKu** [comment]
Can you check stylua?

**Comment by Std-Enigma** [comment]
> Can you check stylua?

Why the code base wasn't formatted before that's why I didn't format it at the first place cause i thought that's just your preference

**Comment by EpsilonKu** [comment]
@Std-Enigma well, idk. The last mr it was formatted. Seems like @windwp pushed commit without formatting. Sorry for bothering.

**Comment by Std-Enigma** [comment]
No worries happy to be part of this amazing plugin

**Pull request merged**
