### PR TITLE
Add highlight

### LINKED ISSUE #123: Add highlight group/customization to layout text
My nvim colorscheme uses an italic font for comments. Spectre's layout separators (`---`, `¦`, etc.) link to the `Comment` group and thus are rendered italic for me, which is not ideal.

```
------------------------------------------ ← italic for me
 scss/sample.scss:27:4:
¦  $local-width: 1000px;
¦  width: $local-width/2;
 lua/iterators.lua:8:1:
¦  local co = coroutine
¦  local f = require "plenary.functional"

↑ italic for me
```

It would be nice to have either have Spectre-specific highlight groups added, or to have the layout text included in the `setup.highlights` table.

Related: #111, #64

### PR DESCRIPTION
**Pull request by EpsilonKu**
Should fix #123 #64 
Will add background later for #111

### CODE REVIEW

**Comment by windwp** [comment]
lua has a function bit.tohex(background,6) to convert hex
we can use a similar function from cmp
https://github.com/hrsh7th/nvim-cmp/blob/main/lua/cmp/utils/highlight.lua

**Comment by EpsilonKu** [comment]
Omg, sorry for late reply. Was busy with diploma project. Will commit as I can.

**Comment by EpsilonKu** [comment]
Made more simpler highlighting. I decided to not link highlight so it won't link italics and bold.

**Comment by windwp** [comment]
Ok, could you  link the 'spectreheader' to the` comment`? 
so it will no affect the original (UI) and you can merge it

**Pull request merged**
