### PR TITLE
Add 'sd' replace method

### PR DESCRIPTION
**Pull request by Zananok**

### CODE REVIEW

**Comment by mathjiajia** [comment]
I guess you need to modify the following:
https://github.com/nvim-pack/nvim-spectre/blob/31f62d7fc30257b2a5c5327ff7b47719da37a1b4/lua/spectre/config.lua#L220-L225

**Comment by Zananok** [comment]
This will change the defaults. My PR is to add 'sd' support, not override the default.

To enable sd:
```
require("spectre").setup {
    default = {
        replace = {
            cmd = "sd"
        }
    },
```

**Comment by mathjiajia** [comment]
No. Even if I set `sd` as default,
these piece of code still will run on macOS https://github.com/nvim-pack/nvim-spectre/blob/31f62d7fc30257b2a5c5327ff7b47719da37a1b4/lua/spectre/config.lua#L220-L225

In the case I removed `gnu-sed`, it will print that notification.

**Comment by Zananok** [comment]
Aha, I understand what you mean now.

However, this code would also run if one set the replace cmd to 'oxi', which is another alternative. I would report it as a bug and not that the current PR is missing.

Though, since I am already in the headspace, I can make another PR fixing the issue 👍.

**Pull request merged**
