### PR TITLE
feat(command): allow user to open file search with command

### PR DESCRIPTION
**Pull request by XXiaoA**

### CODE REVIEW

**Comment by windwp** [comment]
i think better if we input a file path or folder .  input % will expand to current file

**Comment by XXiaoA** [comment]
Good idea! I think we can add more features, like `cwd=xxx`

**Comment by XXiaoA** [comment]
Done!
* no argument or `%` will expand to current file
* argument that can't match `key=value` mean `path=something`
* many arguments that can't match `key=value` will pick the last one
* example: `:Spectre spectre.lua is_insert_mode=true cwd=~/.config/nvim`

**Comment by windwp** [comment]
thank you . it work well . can you add document on readme.md 

> Done!
> 
> * no argument or `%` will expand to current file
> * argument that can't match `key=value` mean `path=something`
> * many arguments that can't match `key=value` will pick the last one
> * example: `:Spectre spectre.lua is_insert_mode=true cwd=~/.config/nvim`

**Comment by XXiaoA** [comment]
Okay, done.

**Comment by windwp** [comment]
thanks

**Pull request merged**
