### PR TITLE
feat:add help window border to better show

### PR DESCRIPTION
**Pull request by Mr-LLLLL**
if not border, this help infomation is difficute to read

### CODE REVIEW

**Comment by EpsilonKu** [comment]
LGTM for me. Later will add options to customize borders. But will wait @windwp for review.

**Comment by Mr-LLLLL** [comment]
thanks, i will close this

**Comment by Mr-LLLLL** [comment]
i am not see your MR for customize borders, so i reopen this MR.

**Comment by EpsilonKu** [comment]
I have this issue.
image

**Comment by Mr-LLLLL** [comment]
> I have this issue. image

may by you can open a issue, this PR just only change  popup.creat function parameter, not affectet anything. 
by the way,  i like your font, could you tell me?

**Comment by EpsilonKu** [comment]
@Mr-LLLLL The font combination of [Cascadia Code](https://github.com/microsoft/cascadia-code) + [Cartograph CF](https://connary.com/cartograph.html) . You can download it from [here](https://github.com/sainnhe/icursive-nerd-font/tree/master)

**Comment by EpsilonKu** [comment]
Ok, merging this. Tomorrow will try to fix it.

**Pull request merged**
